### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by hezral** [bgeVam/pycastr#29]
When run, it shows this

error while loading shared libraries: libgee.so.2: cannot open shared object file: No such file or directory

**Comment by hezral** [comment]
i'm on elementaryOS Loki, i tracked that i had /usr/lib/x86_64-linux-gnu/libgee-0.8.so.2

made a symlink in the same folder as libgee.so.2 and the indicator ran but showed below now. 

/opt/pycastr/src/pycastr-gtk$ ./PycastrIndicator 
Gtk-Message: Failed to load module "pantheon-filechooser-module"
(PycastrIndicator:11585): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
(PycastrIndicator:11585): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
(PycastrIndicator:11585): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
(PycastrIndicator:11585): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
Segmentation fault (core dumped)

**Comment by bgeVam** [comment]
the warning shows up for me too. are you unable to see the indicator?

**Comment by hezral** [comment]
Yeah, it doesn't show up at all.

**Comment by bgeVam** [comment]
try to reboot, if it doesnt work please do: cat /var/log/syslog | grep PycastrIndicator

**Comment by bgeVam** [comment]
you did use the install script, right?

**Comment by bgeVam** [comment]
you did use the install script, right?

**Comment by hezral** [comment]
you did use the install script, right? << Yes
try to reboot, if it doesnt work please do: cat /var/log/syslog | grep PycastrIndicator

Jun  4 17:18:58 ebelskiver gnome-session[8515]: /opt/pycastr/src/pycastr-gtk/PycastrIndicator: error while loading shared libraries: libgee.so.2: cannot open shared object file: No such file or directory
Jun  4 17:23:01 ebelskiver gnome-session[8515]: /home/adi/Applications/pycastr/src/pycastr-gtk/PycastrIndicator: error while loading shared libraries: libgee.so.2: cannot open shared object file: No such file or directory
Jun  4 17:39:03 ebelskiver gnome-session[11839]: (PycastrIndicator:12094): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
Jun  4 17:39:03 ebelskiver gnome-session[11839]: (PycastrIndicator:12094): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
Jun  4 17:39:03 ebelskiver gnome-session[11839]: message repeated 2 times: [ (PycastrIndicator:12094): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",]
Jun  4 18:45:02 ebelskiver gnome-session[1916]: (PycastrIndicator:2178): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
Jun  4 18:45:02 ebelskiver gnome-session[1916]: message repeated 3 times: [ (PycastrIndicator:2178): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",]

**Comment by bgeVam** [comment]
Please try the updated desktop file and update your desktop database with:

sudo update-desktop-database

**Comment by hezral** [comment]
Sorry still doesn't work

**Comment by bgeVam** [comment]
Does Pycastr show up in your appliations menu?
Whats in the log when you start the indicator from there?
And the other way round: what happens when you run /opt/pycastr/src/pycastr-gtk$ ./PycastrIndicator?

**Comment by hezral** [comment]
Does Pycastr show up in your appliations menu?
> No, i copied the .desktop file to my local/share/application folder, ran it same thing.

Whats in the log when you start the indicator from there?
Same as above. 
> un  5 18:27:34 ebelskiver gnome-session[3765]: (PycastrIndicator:5225): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
> Jun  5 18:27:34 ebelskiver gnome-session[3765]: message repeated 3 times: [ (PycastrIndicator:5225): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",]
> 

And the other way round: what happens when you run /opt/pycastr/src/pycastr-gtk$ ./PycastrIndicator?
This is what i did initially. Same thing :disappointed: 
  
            
 
Write
