### ISSUE TITLE
Error with CMake

### ISSUE THREAD

**Issue by Mexx62** [bgeVam/pycastr#31]
Hi!
When using `cmake -DCMAKE_INSTALL_PREFIX=/usr ../`, I have this error: 

> -- Checking for modules 'gtk+-3.0;gee-0.8;appindicator3-0.1;libnotify;python3'
--   No package 'appindicator3-0.1' found
--   No package 'libnotify' found
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  CMakeLists.txt:26 (pkg_check_modules)
-- Configuring incomplete, errors occurred!
See also "/home/aing/pycastr/build/CMakeFiles/CMakeOutput.log".

But if I `apt search libnotify` I can see that libnotify4 is installed. Same for appindicator, where libappindicator3-1 is installed.
I have included the log file.
Thanks in advance for your help!
[CMakeOutput.txt](https://github.com/bgeVam/pycastr/files/1064174/CMakeOutput.txt)

**Comment by bgeVam** [comment]
for appindicator, please install:
libappindicator3-dev

(sudo apt-get install libappindicator3-dev)

for libnotify do the same with "libnotify-dev"

**Comment by Mexx62** [comment]
Those were the missing packets, thanks for your fast answer!
